language: node_js
node_js:
  - "8"
env:
  global:
    - secure: ""
before_script:
  - git config --global user.email "me@atomicptr.de"
  - git config global user.name "Travis CI"
script:
  - yarn
  - yarn build-data
  - yarn build-frontend --production
after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git add dist
  - git commit -m "[travis-ci] auto build $(date +'%F %H:%M %Z')"
  - git push origin master
